DROP TABLE IF EXISTS TRADE_MASTER;

CREATE TABLE TRADE_MASTER (
    TRADE_ID INT AUTO_INCREMENT PRIMARY KEY,
    ENTITY VARCHAR(20) NOT NULL,
    BUY_OR_SALE CHAR(1) CHECK (BUY_OR_SALE IN ('B', 'S')),
    AGREED_FX DECIMAL(10,2) NOT NULL,
    CURRENCY CHAR(3) NOT NULL,
    INSTRUCTION_DATE DATE NOT NULL,
    SETTLEMENT_DATE DATE NOT NULL,
    UNITS INT NOT NULL,
    PRICE_PER_UNIT DECIMAL(10,2) NOT NULL
);
